apiVersion: v1
kind: Service
metadata:
  name: flusk-app
spec:
  ports:
  - port: 5000
    name: flusk-port
  type: NodePort
  selector:
    app: flusk-app
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flusk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flusk-app
  template:
    metadata:
      name: flusk-app
      labels:
        app: flusk-app
        deployment: pks-workshop
    spec:
      containers:
      - image: harbor.pks.pcfdemo.com/demo/workshop-rest-server
        name: flusk-app
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: secret
        - name: DB_DBNAME
          value: demo1
