apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    name: mysql-port
  type: NodePort
  selector:
    app: mysql-backend
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-backend
  template:
    metadata:
      name: mysql-backend
      labels:
        app: mysql-backend
        deployment: pks-workshop
    spec:
      containers:
      - image: harbor.pks.pcfdemo.com/demo/workshop-mysql
        name: mysql-backend
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: demo1
