apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: pvc0001
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test-volume
      mountPath: /usr/share/nginx/html
