apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
#    volumePath: "ds:///vmfs/volumes/5ad064de-8e224be9-c871-000e1e535700/"
    volumePath: "[k8s] NSX-T/ccc"
    fsType: ext4
